### ISSUE TITLE
프로젝트에 Issue & PR 적용하기

### ISSUE THREAD

**Issue by ujkkk** [on-NA/StudyBlog#1]
## 📝 Description
**무엇을?**
- 프로젝트에 Issue & PR 적용하는 방법 조사 & 컨벤션 정하기

**왜?**
- Github를 이용해 효율적인 협업을 위해

## ❗️Todo
- [ ] 이슈에 무엇을 작성할지 상의 후 정하기
- [ ] PR, Commit 규칙 정하기
- [ ] PR 하나 생성 후 해당 이슈에 적용해보기

## ETC
기타사항

**Comment by ujkkk** [comment]
## Issue & PR

이슈탭부터 들어간다

**이슈는 언제 적어야 하나?**

- 무엇을 하든 이슈부터 적고 한다
- 코드 짜기 전에 이슈를 먼저 만든다

(예시)

https://github.com/Runnect/Runnect-Server/issues/191

**이슈에 무엇을?**

- 의견 던지기
- 무엇을 할 것인가
- 누가 할 것인가

**개요**

- 무엇을 할것인가, 왜 할것인가
- todo

이러고 올리기

코멘트로 으로 Todo 한거 결과 올리기

### **방법**

1. devlop (main) 브랜치로 깃 풀
- git checkout devlop
- git pull origin develop
1. 브랜치를 새로 만든다. 이슈마다
- **git branch feature/issue1**  - 브랜치 생성
1. 생성한 브랜치로 체크아웃
- **git checkout feature/issue1** - 브랜치 바꾸기
1. 작업이 끝났으면 커밋, 푸시
- **git commit -m “[#1] mvc 패턴 적용 - 커밋 메시지**
- **git push origin feature/issue-1** - 깃허브 올리기
1. 풀리퀘 생성 - 연결 - 이슈 번호 넣어주기
- 이슈에 연결된다
- 내용 : 수정사항 - 무엇을 수정했고, 왜 수정했고, 어떤 이슈 발생되었는지 3줄 정도

보통 리뷰를 받아야 머지하도록 옵션 지정한다.
